/**
 * inflection 1.13.4(Sequelize 6.37.8의 `^1.13.4` 의존성, MIT, Copyright (c) 2011 Ben Lin)의 복수·단수 규칙 데이터다.
 *
 * `lib/inflection.js`의 `uncountable_words`·`plural_rules`·`singular_rules`를 순서 그대로 옮겼다(스크립트로 추출,
 * 손으로 고치지 않는다). 규칙은 처음 일치한 하나만 적용된다(`_apply_rules`).
 */

/** 규칙 하나: 정규식 원문, 플래그, 치환 문자열(undefined면 그대로 둔다). */
export type InflectionRule = readonly [source: string, flags: string, replacement: string | undefined];

/** 단·복수가 같은 단어(소문자)다. */
export const uncountableWords: readonly string[] = ["accommodation","adulthood","advertising","advice","aggression","aid","air","aircraft","alcohol","anger","applause","arithmetic","assistance","athletics","bacon","baggage","beef","biology","blood","botany","bread","butter","carbon","cardboard","cash","chalk","chaos","chess","crossroads","countryside","dancing","deer","dignity","dirt","dust","economics","education","electricity","engineering","enjoyment","envy","equipment","ethics","evidence","evolution","fame","fiction","flour","flu","food","fuel","fun","furniture","gallows","garbage","garlic","genetics","gold","golf","gossip","gratitude","grief","guilt","gymnastics","happiness","hardware","harm","hate","hatred","health","heat","help","homework","honesty","honey","hospitality","housework","humour","hunger","hydrogen","ice","importance","inflation","information","innocence","iron","irony","jam","jewelry","judo","karate","knowledge","lack","laughter","lava","leather","leisure","lightning","linguine","linguini","linguistics","literature","litter","livestock","logic","loneliness","luck","luggage","macaroni","machinery","magic","management","mankind","marble","mathematics","mayonnaise","measles","methane","milk","minus","money","mud","music","mumps","nature","news","nitrogen","nonsense","nurture","nutrition","obedience","obesity","oxygen","pasta","patience","physics","poetry","pollution","poverty","pride","psychology","publicity","punctuation","quartz","racism","relaxation","reliability","research","respect","revenge","rice","rubbish","rum","safety","scenery","seafood","seaside","series","shame","sheep","shopping","sleep","smoke","smoking","snow","soap","software","soil","spaghetti","species","steam","stuff","stupidity","sunshine","symmetry","tennis","thirst","thunder","timber","traffic","transportation","trust","underwear","unemployment","unity","validity","veal","vegetation","vegetarianism","vengeance","violence","vitality","warmth","wealth","weather","welfare","wheat","wildlife","wisdom","yoga","zinc","zoology"];

/** 복수화 규칙이다. */
export const pluralRules: readonly InflectionRule[] = [
  ["^(m|wom)en$", "gi", undefined],
  ["(pe)ople$", "gi", undefined],
  ["(child)ren$", "gi", undefined],
  ["([ti])a$", "gi", undefined],
  ["((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$", "gi", undefined],
  ["(database)s$", "gi", undefined],
  ["(drive)s$", "gi", undefined],
  ["(hi|ti)ves$", "gi", undefined],
  ["(curve)s$", "gi", undefined],
  ["([lr])ves$", "gi", undefined],
  ["([^fo])ves$", "gi", undefined],
  ["([^aeiouy]|qu)ies$", "gi", undefined],
  ["(s)eries$", "gi", undefined],
  ["(m)ovies$", "gi", undefined],
  ["(x|ch|ss|sh)es$", "gi", undefined],
  ["([m|l])ice$", "gi", undefined],
  ["(bus)es$", "gi", undefined],
  ["(o)es$", "gi", undefined],
  ["(shoe)s$", "gi", undefined],
  ["(cris|ax|test)es$", "gi", undefined],
  ["(octop|vir)uses$", "gi", undefined],
  ["(alias|canvas|status|campus)es$", "gi", undefined],
  ["^(summons|bonus)es$", "gi", undefined],
  ["^(ox)en", "gi", undefined],
  ["(matr)ices$", "gi", undefined],
  ["^feet$", "gi", undefined],
  ["^teeth$", "gi", undefined],
  ["^geese$", "gi", undefined],
  ["(quiz)zes$", "gi", undefined],
  ["^(whereas)es$", "gi", undefined],
  ["^(criteri)a$", "gi", undefined],
  ["^genera$", "gi", undefined],
  ["^(m|wom)an$", "gi", "$1en"],
  ["(pe)rson$", "gi", "$1ople"],
  ["(child)$", "gi", "$1ren"],
  ["(drive)$", "gi", "$1s"],
  ["^(ox)$", "gi", "$1en"],
  ["(ax|test)is$", "gi", "$1es"],
  ["(octop|vir)us$", "gi", "$1uses"],
  ["(alias|status|canvas|campus)$", "gi", "$1es"],
  ["^(summons|bonus)$", "gi", "$1es"],
  ["(bu)s$", "gi", "$1ses"],
  ["(buffal|tomat|potat)o$", "gi", "$1oes"],
  ["([ti])um$", "gi", "$1a"],
  ["sis$", "gi", "ses"],
  ["(?:([^f])fe|([lr])f)$", "gi", "$1$2ves"],
  ["(hi|ti)ve$", "gi", "$1ves"],
  ["([^aeiouy]|qu)y$", "gi", "$1ies"],
  ["(matr)ix$", "gi", "$1ices"],
  ["(vert|ind)ex$", "gi", "$1ices"],
  ["(x|ch|ss|sh)$", "gi", "$1es"],
  ["([m|l])ouse$", "gi", "$1ice"],
  ["^foot$", "gi", "feet"],
  ["^tooth$", "gi", "teeth"],
  ["^goose$", "gi", "geese"],
  ["(quiz)$", "gi", "$1zes"],
  ["^(whereas)$", "gi", "$1es"],
  ["^(criteri)on$", "gi", "$1a"],
  ["^genus$", "gi", "genera"],
  ["s$", "gi", "s"],
  ["$", "gi", "s"],
];

/** 단수화 규칙이다. */
export const singularRules: readonly InflectionRule[] = [
  ["^(m|wom)an$", "gi", undefined],
  ["(pe)rson$", "gi", undefined],
  ["(child)$", "gi", undefined],
  ["(drive)$", "gi", undefined],
  ["^(ox)$", "gi", undefined],
  ["(ax|test)is$", "gi", undefined],
  ["(octop|vir)us$", "gi", undefined],
  ["(alias|status|canvas|campus)$", "gi", undefined],
  ["^(summons|bonus)$", "gi", undefined],
  ["(bu)s$", "gi", undefined],
  ["(buffal|tomat|potat)o$", "gi", undefined],
  ["([ti])um$", "gi", undefined],
  ["sis$", "gi", undefined],
  ["(?:([^f])fe|([lr])f)$", "gi", undefined],
  ["(hi|ti)ve$", "gi", undefined],
  ["([^aeiouy]|qu)y$", "gi", undefined],
  ["(x|ch|ss|sh)$", "gi", undefined],
  ["(matr)ix$", "gi", undefined],
  ["([m|l])ouse$", "gi", undefined],
  ["^foot$", "gi", undefined],
  ["^tooth$", "gi", undefined],
  ["^goose$", "gi", undefined],
  ["(quiz)$", "gi", undefined],
  ["^(whereas)$", "gi", undefined],
  ["^(criteri)on$", "gi", undefined],
  ["^genus$", "gi", undefined],
  ["^(m|wom)en$", "gi", "$1an"],
  ["(pe)ople$", "gi", "$1rson"],
  ["(child)ren$", "gi", "$1"],
  ["(database)s$", "gi", "$1"],
  ["(drive)s$", "gi", "$1"],
  ["^genera$", "gi", "genus"],
  ["^(criteri)a$", "gi", "$1on"],
  ["([ti])a$", "gi", "$1um"],
  ["((a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he)ses$", "gi", "$1$2sis"],
  ["(hi|ti)ves$", "gi", "$1ve"],
  ["(curve)s$", "gi", "$1"],
  ["([lr])ves$", "gi", "$1f"],
  ["([a])ves$", "gi", "$1ve"],
  ["([^fo])ves$", "gi", "$1fe"],
  ["(m)ovies$", "gi", "$1ovie"],
  ["([^aeiouy]|qu)ies$", "gi", "$1y"],
  ["(s)eries$", "gi", "$1eries"],
  ["(x|ch|ss|sh)es$", "gi", "$1"],
  ["([m|l])ice$", "gi", "$1ouse"],
  ["(bus)es$", "gi", "$1"],
  ["(o)es$", "gi", "$1"],
  ["(shoe)s$", "gi", "$1"],
  ["(cris|ax|test)es$", "gi", "$1is"],
  ["(octop|vir)uses$", "gi", "$1us"],
  ["(alias|canvas|status|campus)es$", "gi", "$1"],
  ["^(summons|bonus)es$", "gi", "$1"],
  ["^(ox)en", "gi", "$1"],
  ["(matr)ices$", "gi", "$1ix"],
  ["(vert|ind)ices$", "gi", "$1ex"],
  ["^feet$", "gi", "foot"],
  ["^teeth$", "gi", "tooth"],
  ["^geese$", "gi", "goose"],
  ["(quiz)zes$", "gi", "$1"],
  ["^(whereas)es$", "gi", "$1"],
  ["ss$", "gi", "ss"],
  ["s$", "gi", ""],
];
