import assert from 'node:assert/strict';
import { test } from 'node:test';

import { ormLines } from './testing.test.ts';

test('값 평가: 이름공간·재수출·CommonJS·import=·조건·대체 연산자·타입 별칭·ReturnType·교차 타입·객체 스키마', () => {
  assert.deepEqual(ormLines({
  'src/lib/pool.ts': "import pg = require('pg');\nexport const pool = new pg.Pool();\nexport default pool;\n",
  'src/lib/index.ts': "export * from './pool';\nexport { default as defaultPool } from './pool';\n",
  'src/lib/cjs.js': "const Pool = require('pg').Pool;\nconst { Client: PgClient } = require('pg');\nmodule.exports = { pool: new Pool(), client: new PgClient() };\n",
  'src/q.ts': [
    "import * as lib from './lib';",
    "import cjs = require('./lib/cjs');",
    "import type { Knex } from 'knex';",
    "import knexFactory from 'knex';",
    "import { sqliteTable, integer } from 'drizzle-orm/sqlite-core';",
    "import { drizzle } from 'drizzle-orm/better-sqlite3';",
    "import { relations } from 'drizzle-orm';",
    "export const things = sqliteTable('things', { id: integer() });",
    "export const parts = sqliteTable('parts', { id: integer(), thingId: integer('thing_id') });",
    "export const thingRelations = relations(things, function ({ many }) { return { parts: many(parts) }; });",
    'const schemaParts = { parts };',
    'const db = drizzle(\'file\', { schema: { ...schemaParts, things, ignored: 1 } });',
    'function makeKnex(): Knex { return knexFactory({}); }',
    'type Trx = Knex.Transaction & { tag?: string };',
    'let cached: ReturnType<typeof makeKnex> | null = null;',
    'export async function run(flag: boolean, trx: Trx, maybe?: Knex | undefined) {',
    "  await lib.pool.query('select * from ns_pool');",
    "  await lib.defaultPool.query('select * from ns_default');",
    "  await lib['pool'].query('select * from ns_element');",
    "  await cjs.pool.query('select * from cjs_pool');",
    "  await cjs.client.query('select * from cjs_client');",
    "  const chosen = flag ? lib.pool : null;",
    "  await chosen!.query('select * from cond_pool');",
    "  await (cached ?? makeKnex())('fallback_rows');",
    "  await trx('trx_rows');",
    "  await maybe!('maybe_rows');",
    "  await (flag ? trx : maybe!)('either_rows');",
    '  const reader = async () => makeKnex();',
    "  await (await reader())('arrow_rows');",
    "  return db.query.things.findMany({ with: { parts: true } });",
    '}',
    '',
  ].join('\n'),
}), [
    'src/q.ts:8:35 things @src/q.ts#model:things',
    'src/q.ts:8:47 things.id @src/q.ts#model:things.id',
    'src/q.ts:9:34 parts @src/q.ts#model:parts',
    'src/q.ts:9:45 parts.id @src/q.ts#model:parts.id',
    'src/q.ts:9:60 parts.thing_id @src/q.ts#model:parts.thingId',
    'src/q.ts:17:24 ns_pool @src/q.ts#run',
    'src/q.ts:18:31 ns_default @src/q.ts#run',
    'src/q.ts:19:27 ns_element @src/q.ts#run',
    'src/q.ts:20:24 cjs_pool @src/q.ts#run',
    'src/q.ts:21:26 cjs_client @src/q.ts#run',
    'src/q.ts:23:23 cond_pool @src/q.ts#run',
    'src/q.ts:24:32 fallback_rows @src/q.ts#run',
    'src/q.ts:25:13 trx_rows @src/q.ts#run',
    'src/q.ts:26:16 maybe_rows @src/q.ts#run',
    'src/q.ts:27:31 either_rows @src/q.ts#run',
    'src/q.ts:29:26 arrow_rows @src/q.ts#run',
    'src/q.ts:30:19 things @src/q.ts#run',
    'src/q.ts:30:45 parts @src/q.ts#run',
  ]);
});
